* SpiraJira: Cut Through the Scum

  #+BEGIN_QUOTE
  Spirogyra is very common in relatively clean eutrophic water,
  developing slimy filamentous green masses. In spring Spirogyra grows
  under water, but when there is enough sunlight and warmth they
  produce large amounts of oxygen, adhering as bubbles between the
  tangled filaments. The filamentous masses come to the surface and
  become visible as slimy green mats.  (Wikipedia)
  #+END_QUOTE

  A crude command-line client for Jira.  If you have to use it, at
least you won't have to touch it.

* Commands

** Show an Issue

   Prints the Summary, Description, and Comments for the specified Ticket:

   #+BEGIN_SRC sh
   $ spirajira TB-001
   #+END_SRC

   #+BEGIN_SRC fundamental
     TB-001 :: On the Many Problems Inherent in Mis-using Jira for Planning
     [In Development]

     This hurts.  Why do we keep doing this to ourselves?

     COMMENTS:

     Joe Dev (2015-02-27 00:02:23 UTC)
     But I like doing it this way.  I never have to talk to anybody and
     it's nearly impossible for anyone to find out how terrible I am at
     my job.
   #+END_SRC

** Comment on an Issue

   Add a comment to the specified ticket.

   #+BEGIN_SRC sh
   $ spirajira comment TB-002 "I sure wish we weren't trying to plan software with a ticketing tool"
   #+END_SRC

** Show Available Transitions

   #+BEGIN_SRC sh
   $ spirajira actions TB-001
   #+END_SRC

   #+BEGIN_SRC fundamental
   31 : Pause Development
   211 : Developed - Waiting for Product Review
   311 : In Development - Waiting for Product Info
   371 : Close
   #+END_SRC

** Trigger a Transition

   #+BEGIN_SRC sh
   $ spirajira act TB-001 371
   #+END_SRC

* Installation

  Hold on.  Let's make sure it works first.

  If you really want to try it, there's a build of it for [[https://github.com/tobytripp/SpiraJira/releases/tag/v0.1.0.0][OS/X]].
  Otherwise, check it out and build it with [[https://www.haskell.org/cabal/][cabal]]:

  #+BEGIN_SRC sh
    cabal install --only-dependencies
    cabal build
  #+END_SRC

* Configuration

  SpiraJira reads login credentials and Server URI from a configuration file.

  By default, it will read files in this order:
    1. $(HOME)/.spirajira
    2. ./spirajira.cfg
    3. a file specified with the =--config= option

  The configuration file should look something like this:

  #+BEGIN_SRC conf
    user = "ticketdrone557"
    pass = "comply!"
    uri  = "https://jira.host/rest/api/2/"
  #+END_SRC


